### ISSUE TITLE
Connection Timeout Issue

### ISSUE THREAD

**Issue by pranayreddi** [mpangrazzi/save-to-mongo#2]
Hi,

When I'm trying to run save-to-mongo, connection timeout error. Please suggest how to set the connection timeout parameter or the below error? 

/node_modules/save-to-mongo/node_modules/mongodb/lib/mongodb/mongo_client.js:409
          throw err
          ^
TypeError: Cannot read property 'collection' of null
    at node_modules/save-to-mongo/lib/index.js:110:32
    at node_modules/save-to-mongo/node_modules/mongodb/lib/mongodb/mongo_client.js:406:11
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Thanks in Advance.

**Comment by mpangrazzi** [comment]
Hi,

you're right, and this is caused by outdated `mongodb` and `monk` modules. I've to update them and do some module maintenance. I'll keep this issue updated.

**Comment by mpangrazzi** [comment]
This is now solved. Please use version `1.0.0`, already published on [NPM](https://www.npmjs.com/package/save-to-mongo)
